// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	artmgmt "github.com/gustavooferreira/news-app-fetcher-service/pkg/clients/artmgmt"

	mock "github.com/stretchr/testify/mock"
)

// ArticlesClient is an autogenerated mock type for the ArticlesClient type
type ArticlesClient struct {
	mock.Mock
}

// AddArticles provides a mock function with given fields: articles
func (_m *ArticlesClient) AddArticles(articles artmgmt.Articles) error {
	ret := _m.Called(articles)

	var r0 error
	if rf, ok := ret.Get(0).(func(artmgmt.Articles) error); ok {
		r0 = rf(articles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
