// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	feedmgmt "github.com/gustavooferreira/news-app-fetcher-service/pkg/clients/feedmgmt"
	mock "github.com/stretchr/testify/mock"
)

// FeedsClient is an autogenerated mock type for the FeedsClient type
type FeedsClient struct {
	mock.Mock
}

// GetFeeds provides a mock function with given fields: provider, category, enabled
func (_m *FeedsClient) GetFeeds(provider string, category string, enabled bool) (feedmgmt.Feeds, error) {
	ret := _m.Called(provider, category, enabled)

	var r0 feedmgmt.Feeds
	if rf, ok := ret.Get(0).(func(string, string, bool) feedmgmt.Feeds); ok {
		r0 = rf(provider, category, enabled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(feedmgmt.Feeds)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(provider, category, enabled)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
